datasource:
  mysql1:
    url: 'jdbc:mysql://xx.xx.xx.xx:3306/db1?&useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull'
    username: 'root'
    password: '****'
  mysql2:
    url: 'jdbc:mysql://xx.xx.xx.xx:3306/db2?&useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull'
    username: 'root'
    password: '****'


